### ISSUE TITLE
A work to add

### ISSUE THREAD

**Issue by mathilde-b** [YuejiangLIU/awesome-source-free-test-time-adaptation#1]
Hello Yuejiang Liu,
Thanks for compiling this nice list.
I just wanted to point out our 2020 MICCAI work: Source Free Domain Adaptation for Image Segmentation, which could be a nice addition to your list.
https://arxiv.org/abs/2108.03152
Cheers !
Mathilde

**Comment by YuejiangLIU** [comment]
Hi Mathilde,

Thanks for sharing that. Have just incorporated your work into the list. 

Thanks,
Yuejiang
