### ISSUE TITLE
Request to add paper

### ISSUE THREAD

**Issue by xidulu** [YuejiangLIU/awesome-source-free-test-time-adaptation#11]
Hi

My work [1] on ICLR 2023 proposes a new test time adaptation layer called ShiftMatch that matches the second order statistics of the test features to that of the training features for better robustness, I am wondering if it can fit into the feature alignment or the batch normalization section in this list.

[1] https://openreview.net/forum?id=kUI41mY8bHl

Thanks,
Xi

**Comment by YuejiangLIU** [comment]
Thanks! Have added your ShiftMatch to the list :)
