### ISSUE TITLE
Request to add a paper

### ISSUE THREAD

**Issue by Yushu-Li** [YuejiangLIU/awesome-source-free-test-time-adaptation#17]
Hi Yuejiang,

Thanks for maintaining this awesome list!

I would like to request to add our paper: "On the Robustness of Open-World Test-Time Training: Self-Training with Dynamic Prototype Expansion" (**ICCV 2023 Oral**).

ArXiv: https://arxiv.org/abs/2308.09942
Code: https://github.com/Yushu-Li/OWTTT
Project page: https://yushu-li.github.io/owttt-site/

In this work, we consider the problem of test-time adaptation in open-world scenarios for the first time. Furthermore, we used the self-training method based on prototype expansion to achieve SOTA performance under the proposed protocol. I think this paper belongs to both "Class Prototype", "Self-supervision", and a new category "Open World".

Thanks for considering this.
Yushu Li

**Comment by YuejiangLIU** [comment]
Hi Yushu, thanks for sharing your interesting work! 

I've just added it into `Class Prototype` and `Self-supervision` categories. The paper list is primarily structured by method at the moment. I'd be happy to create a `Open World` category though, if there are more research efforts delve into this setting in the future.
