### ISSUE TITLE
Request to add a paper

### ISSUE THREAD

**Issue by chi-chi-zx** [YuejiangLIU/awesome-source-free-test-time-adaptation#3]
Hi Yuejiang,

Thanks for maintaining the list! We would like to request to add our NeurIPS2022 paper: "Meta-DMoE: Adapting to Domain Shift by Meta-Distillation from Mixture-of-Experts". We formulate the source free test time adaptation as the knowledge distillation process to solve the domain shift problem. At test-time, the model is adapted to a target domain using unlabeled data in an unsupervised manner.

Thanks.

**Comment by YuejiangLIU** [comment]
Thanks for sharing the one-sentence summary. Have just added your paper to the list.

Thanks,
Yuejiang
